/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.machacas.Vista;

import Controlador.EscribirMNZ;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author josue
 */
public class Ventana_Manzanillo extends javax.swing.JDialog {

    /**
     * Creates new form Ventana_Manzanillo
     */
    public Ventana_Manzanillo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Factura Manzanillo");
        setBounds(50, 50, 783, 500);
        jtfObtXML.setEnabled(false);
        Border bordeB = new TitledBorder("Buque");
        Border bordeV = new TitledBorder("Viaje");
        Border bordeAi = new TitledBorder("Fecha Atraque Inicial");
        Border bordeAn = new TitledBorder("Fecha Atraque Final");
        Border bordeR = new TitledBorder("Referencia");
        Border bordeN = new TitledBorder("Número referencia");
        Border borderVa = new TitledBorder("Valor de la factura");
        Border borderD = new TitledBorder("Dollar");

        jtfBuque.setBorder(bordeB);
        jtfViaje.setBorder(bordeV);
        jtfFechaInicial.setBorder(bordeAi);
        jtfFechaFinal.setBorder(bordeAn);
        jtfReferencia.setBorder(bordeR);
        jtfNumR.setBorder(bordeN);
        jtfValorFac.setBorder(borderVa);
        jtfDolar.setBorder(borderD);
        jtfDolar.setColumns(8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        pNorte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pSur = new javax.swing.JPanel();
        jtfDolar = new javax.swing.JTextField();
        btnEscribir = new javax.swing.JButton();
        jtfObtXML = new javax.swing.JTextField();
        pCentral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtfBuque = new javax.swing.JTextField();
        jtfFechaInicial = new javax.swing.JTextField();
        jtfReferencia = new javax.swing.JTextField();
        jtfViaje = new javax.swing.JTextField();
        jtfFechaFinal = new javax.swing.JTextField();
        jtfNumR = new javax.swing.JTextField();
        jtfValorFac = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pPrincipal.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\josue.ochoa\\OneDrive - AUTOMOTIVE LOGISTICS S.C\\Documents\\NetBeansProjects\\Prueba\\src\\main\\java\\imagenes\\Cotecon.PNG")); // NOI18N
        pNorte.add(jLabel1);

        pPrincipal.add(pNorte, java.awt.BorderLayout.PAGE_START);

        pSur.add(jtfDolar);

        btnEscribir.setText("Escribir y convertir");
        btnEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirActionPerformed(evt);
            }
        });
        pSur.add(btnEscribir);

        jtfObtXML.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        pSur.add(jtfObtXML);

        pPrincipal.add(pSur, java.awt.BorderLayout.PAGE_END);

        pCentral.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jPanel2.setLayout(new java.awt.GridLayout(2, 2));
        jPanel2.add(jtfBuque);
        jPanel2.add(jtfFechaInicial);
        jPanel2.add(jtfReferencia);

        jtfViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfViajeActionPerformed(evt);
            }
        });
        jPanel2.add(jtfViaje);
        jPanel2.add(jtfFechaFinal);
        jPanel2.add(jtfNumR);

        jPanel1.add(jPanel2);
        jPanel1.add(jtfValorFac);

        pCentral.add(jPanel1, java.awt.BorderLayout.CENTER);

        pPrincipal.add(pCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(pPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirActionPerformed
        if (jtfBuque.getText().isEmpty() || jtfViaje.getText().isEmpty() || jtfFechaInicial.getText().isEmpty()
                || jtfFechaFinal.getText().isEmpty() || jtfReferencia.getText().isEmpty() || jtfNumR.getText().isEmpty()||
                jtfValorFac.getText().isEmpty()|| jtfDolar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tienes campos vacios", "¡Campos vacios!", JOptionPane.WARNING_MESSAGE);
        } else {
            EscribirMNZ es = new EscribirMNZ();
            es.escrituraMNZ(jtfBuque.getText().toUpperCase(), jtfViaje.getText().toUpperCase(),
                    jtfFechaInicial.getText(), jtfFechaFinal.getText(),
                    jtfReferencia.getText().toUpperCase(), jtfNumR.getText().toUpperCase(),jtfValorFac.getText().toUpperCase(),jtfDolar.getText());
            JOptionPane.showMessageDialog(this, "Se genero un nuevo pdf ", "¡Nueva factura!", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }

    }//GEN-LAST:event_btnEscribirActionPerformed

    private void jtfViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfViajeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscribir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtfBuque;
    private javax.swing.JTextField jtfDolar;
    private javax.swing.JTextField jtfFechaFinal;
    private javax.swing.JTextField jtfFechaInicial;
    private javax.swing.JTextField jtfNumR;
    public static javax.swing.JTextField jtfObtXML;
    private javax.swing.JTextField jtfReferencia;
    private javax.swing.JTextField jtfValorFac;
    private javax.swing.JTextField jtfViaje;
    private javax.swing.JPanel pCentral;
    private javax.swing.JPanel pNorte;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JPanel pSur;
    // End of variables declaration//GEN-END:variables
}
