/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.machacas.Vista;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author josue.ochoa
 */
public class VisorPDF extends javax.swing.JFrame {

    /**
     * Creates new form VisorPDF
     */
    public VisorPDF() {
        initComponents();

        this.cbFacturas.addItem("SSA");
        this.cbFacturas.addItem("Manzanillo");
        this.cbFacturas.addItem("HTP");
        btnConvertir.setEnabled(false);
        Border borderP = new TitledBorder("Plantilla PDF");
        Border borderV = new TitledBorder("Visor PDF");
        jScrollPane1.setBorder(borderP);
        jScrollPane2.setBorder(borderV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelSur = new javax.swing.JPanel();
        tfRutaXML = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        panelNorte = new javax.swing.JPanel();
        cbFacturas = new javax.swing.JComboBox<>();
        btnAgregarXML = new javax.swing.JButton();
        panelCentro = new javax.swing.JPanel();
        panelIzquierda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelDerecha = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setLayout(new java.awt.BorderLayout());

        tfRutaXML.setText("Ruta XML ");
        panelSur.add(tfRutaXML);

        btnConvertir.setText("Convertir");
        panelSur.add(btnConvertir);

        panelMain.add(panelSur, java.awt.BorderLayout.PAGE_END);

        cbFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFacturasActionPerformed(evt);
            }
        });
        panelNorte.add(cbFacturas);

        btnAgregarXML.setText("Agregar XML");
        btnAgregarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarXMLActionPerformed(evt);
            }
        });
        panelNorte.add(btnAgregarXML);

        panelMain.add(panelNorte, java.awt.BorderLayout.PAGE_START);

        panelCentro.setLayout(new java.awt.GridLayout(1, 2));

        panelIzquierda.setLayout(new java.awt.BorderLayout());
        panelIzquierda.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelCentro.add(panelIzquierda);

        panelDerecha.setLayout(new java.awt.BorderLayout());
        panelDerecha.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panelCentro.add(panelDerecha);

        panelMain.add(panelCentro, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarXMLActionPerformed
        // TODO add your handling code here:
        String facturaSelec = (String) cbFacturas.getSelectedItem();
        switch (facturaSelec) {
            case "Manzanillo":
                Ventana_Manzanillo vm = new Ventana_Manzanillo(this, true);
                vm.setVisible(true);
                break;
            case "SSA":
                Ventana_SSA sa = new Ventana_SSA(this, true);
                sa.setVisible(true);
                break;
            case "HTP":
                Ventana_HTP vh = new Ventana_HTP(this, true);
                vh.setVisible(true);
                break;
            default:
                //System.exit(0);
                JOptionPane.showMessageDialog(null, "No has seleccionado una factura",
                        "Selecciona alguna factura", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnAgregarXMLActionPerformed

    private void cbFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFacturasActionPerformed
        String facturaSelec = (String) cbFacturas.getSelectedItem();
        switch (facturaSelec) {
            case "Manzanillo":
                openpdf("C:\\Users\\josue.ochoa\\Downloads\\FacturaMNZ.pdf");
                break;
            case "SSA":
                System.out.println("Ejele");
                break;
            case "HTP":
                System.out.println("Ejele2");
                break;
            default:
                //System.exit(0);
                JOptionPane.showMessageDialog(null, "No has seleccionado una factura",
                        "Selecciona alguna factura", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cbFacturasActionPerformed

    void openpdf(String file) {
        try {
            SwingController control = new SwingController();
            SwingViewBuilder factry = new SwingViewBuilder(control);
            JPanel veiwerCompntpnl = factry.buildViewerPanel();
            ComponentKeyBinding.install(control, veiwerCompntpnl);
            control.getDocumentViewController().setAnnotationCallback(
                    new org.icepdf.ri.common.MyAnnotationCallback(
                            control.getDocumentViewController()));
            control.openDocument(file);
            jScrollPane1.setViewportView(veiwerCompntpnl);
            jScrollPane1.getVerticalScrollBar().setPreferredSize(
                    new Dimension(10, Integer.MAX_VALUE));
            jScrollPane1.getHorizontalScrollBar().setPreferredSize(
                    new Dimension(Integer.MAX_VALUE, 10));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Cannot Load Pdf");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarXML;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> cbFacturas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JTextField tfRutaXML;
    // End of variables declaration//GEN-END:variables
}
