/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.machacas.Vista;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author josue
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        cbFacturas.addItem("SSA");
        cbFacturas.addItem("Manzanillo");
        cbFacturas.addItem("HTP");
        btnConvertir.setEnabled(false);
        Border bordepanel = new TitledBorder("Plantilla PDF");
        Border bordepane2 = new TitledBorder(" Visor PDF");
        Border borderText = new TitledBorder(" ");
        //scrolPanel.setBorder(bordepanel);
        jCentro.setBorder(bordepane2);
        jSur.setBorder(borderText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jNorte = new javax.swing.JPanel();
        cbFacturas = new javax.swing.JComboBox<>();
        btnConvertir = new javax.swing.JButton();
        jCentro = new javax.swing.JPanel();
        jSur = new javax.swing.JPanel();
        jtfRutaXML = new javax.swing.JTextField();
        btnAgregarXML = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jNorte.setLayout(new java.awt.GridLayout());
        getContentPane().add(jNorte, java.awt.BorderLayout.CENTER);

        cbFacturas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(cbFacturas, java.awt.BorderLayout.CENTER);

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvertir, java.awt.BorderLayout.PAGE_START);

        jCentro.setLayout(new java.awt.GridLayout(1, 2));
        getContentPane().add(jCentro, java.awt.BorderLayout.LINE_END);

        jtfRutaXML.setText("Borrar antes de agregar");
        jtfRutaXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRutaXMLActionPerformed(evt);
            }
        });

        btnAgregarXML.setText("Agregar XML");
        btnAgregarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jSurLayout = new javax.swing.GroupLayout(jSur);
        jSur.setLayout(jSurLayout);
        jSurLayout.setHorizontalGroup(
            jSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfRutaXML, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
            .addGroup(jSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jSurLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnAgregarXML, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jSurLayout.setVerticalGroup(
            jSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSurLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfRutaXML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jSurLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnAgregarXML, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jSur, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        String facturaSelec = (String) cbFacturas.getSelectedItem();
        switch (facturaSelec) {
            case "Manzanillo":
                Ventana_Manzanillo vm = new Ventana_Manzanillo(this, true);
                vm.setVisible(true);
               // openpdf("C:\\Users\\josue.ochoa\\Downloads\\FacturaMNZ.pdf");
                break;
            case "SSA":
                Ventana_SSA sa = new Ventana_SSA(this, true);
                sa.setVisible(true);
                break;
            case "HTP":
                Ventana_HTP vh = new Ventana_HTP(this, true);
                vh.setVisible(true);
                break;
            default:
                //System.exit(0);
                JOptionPane.showMessageDialog(null, "No has seleccionado una factura", "Selecciona alguna factura", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnConvertirActionPerformed

    private void jtfRutaXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRutaXMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRutaXMLActionPerformed

    private void btnAgregarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarXMLActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Selecciona:", "xml");
        fileChooser.setFileFilter(filter);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            this.jtfRutaXML.setText(fileChooser.getSelectedFile().getAbsolutePath());
            btnConvertir.setEnabled(true);
        }
    }//GEN-LAST:event_btnAgregarXMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarXML;
    public javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> cbFacturas;
    private javax.swing.JPanel jCentro;
    private javax.swing.JPanel jNorte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jSur;
    private javax.swing.JTextField jtfRutaXML;
    // End of variables declaration//GEN-END:variables

    

}
